package vn.edu.vtiacademy.test;// Generated by Selenium IDE
import java.util.HashMap;
import java.util.Map;
import org.openqa.selenium.By;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.chrome.ChromeOptions;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.interactions.Actions;
import org.testng.annotations.AfterMethod;
import org.testng.annotations.BeforeMethod;
import org.testng.annotations.Test;

public class DemoTest {

  JavascriptExecutor js;
  private WebDriver driver;
  private Map<String, Object> vars;

  @BeforeMethod
  public void setUp() {
    System.setProperty("webdriver.chrome.driver", "/Users/tuyenluu/training-workspace/VTI_AT_202602/ATTestingFramework/drivers/chromedriver-mac-x64/chromedriver");
    ChromeOptions options = new ChromeOptions();
    options.addArguments("--remote-allow-origins=*");
    driver = new ChromeDriver(options);
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }

  @AfterMethod
  public void tearDown() {
    driver.quit();
  }

  @Test
  public void untitled() {
    driver.get("https://demoqa.com/webtables");
    driver.manage().window().setSize(new Dimension(2048, 1250));
    {
      WebElement element = driver.findElement(By.id("addNewRecordButton"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    driver.findElement(By.id("addNewRecordButton")).click();
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    driver.findElement(By.id("firstName")).click();
    driver.findElement(By.id("firstName")).sendKeys("Kevin");
    driver.findElement(By.id("lastName")).sendKeys("Gao");
    driver.findElement(By.id("userEmail")).sendKeys("kevingao@mailinator.com");
    driver.findElement(By.id("age")).sendKeys("34");
    driver.findElement(By.id("salary")).sendKeys("3500");
    driver.findElement(By.id("department")).sendKeys("IT");
    driver.findElement(By.id("submit")).click();
//    {
//      WebElement element = driver.findElement(By.id("submit"));
//      Actions builder = new Actions(driver);
//      builder.moveToElement(element).perform();
//    }
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    driver.close();
  }
}
